web/router.ex
defmodule Steps.Router do
  use Steps.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser_user_authenticated do
    plug Guardian.Plug.EnsureAuthenticated, handler: Steps.Auth.Browser
  end

  pipeline :api do
    plug :accepts, ["json"]

    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  pipeline :api_user_authenticated do
    plug Guardian.Plug.EnsureAuthenticated, handler: Steps.Auth.API
  end

  scope "/", Steps do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", Steps do
    pipe_through [:browser, :browser_user_authenticated]

    resources "/goals", GoalController do
      resources "/steps", StepController, except: [:index, :show]
    end
  end

  scope "/api", Steps.API, as: :api do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/sessions", SessionController, only: [:create]
      resources "/users", UserController, only: [:create]
    end

    scope "/v1", V1, as: :v1 do
      pipe_through :api_user_authenticated

      resources "/goals", GoalController, except: [:new, :edit]
      resources "/steps", StepController, except: [:new, :edit]
    end
  end
end

web/views/layout_view.ex
defmodule Steps.LayoutView do
  use Steps.Web, :view

  def title(conn, base_title) do
    try do
      [
        apply(view_module(conn), :title, [action_name(conn), conn]),
        base_title
      ] |> Enum.join(" | ")
    rescue _ ->
      base_title
    end
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= title @conn, "Steps" %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <div class="container">
      <header class="top-header-container">
        <div class="top-header-row header-row">
          <h1 class="logo">
            <%= link "Steps", to: "/" %>
          </h1>
          <ul class="session-info">
            <%= if Steps.Auth.current_user(@conn) do %>
              <li><%= Steps.Auth.current_user(@conn).username %></li>
              <li>
                <%= link "Log out",
                         to: session_path(@conn, :delete, Steps.Auth.current_user(@conn)),
                         method: "delete" %>
              </li>
            <% else %>
              <li><%= link "Register", to: user_path(@conn, :new) %></li>
              <li><%= link "Log in", to: session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </div>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main" class="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <script type="text/javascript">
      $(function () {
        $('[data-toggle="popover"]').webuiPopover()
      })
    </script>
  </body>
</html>