web/router.ex
defmodule Steps.Router do
  use Steps.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser_user_authenticated do
    plug Guardian.Plug.EnsureAuthenticated, handler: Steps.Auth.Browser
  end

  pipeline :api do
    plug :accepts, ["json"]

    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  pipeline :api_user_authenticated do
    plug Guardian.Plug.EnsureAuthenticated, handler: Steps.Auth.API
  end

  scope "/", Steps do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", Steps do
    pipe_through [:browser, :browser_user_authenticated]

    resources "/goals", GoalController do
      resources "/steps", StepController, except: [:index, :show]
    end
  end

  scope "/api", Steps.API, as: :api do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/sessions", SessionController, only: [:create]
      resources "/users", UserController, only: [:create]
    end

    scope "/v1", V1, as: :v1 do
      pipe_through :api_user_authenticated

      resources "/goals", GoalController, except: [:new, :edit]
      resources "/steps", StepController, except: [:new, :edit]
    end
  end
end

web/models/goal.ex
defmodule Steps.Goal do
  use Steps.Web, :model

  alias Steps.{User, Step}

  schema "goals" do
    field :name, :string
    field :description, :string
    belongs_to :user, User
    has_many :steps, Step

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :description])
    |> validate_required([:name])
  end

  def for_user(user) do
    assoc(user, :goals)
  end

  def for_user(user, with_steps: true) do
    from g in for_user(user), preload: :steps
  end
end

web/controllers/api/v1/goal_controller.ex
defmodule Steps.API.V1.GoalController do
  use Steps.Web, :controller
  alias Steps.{Auth, Goal, Repo}

  def index(conn, _) do
    goals =
      conn
      |> Auth.current_user
      |> Goal.for_user
      |> Repo.all

    render conn, "index.json", %{goals: goals}
  end

  def show(conn, %{"id" => id}) do
    goal =
      conn
      |> Auth.current_user
      |> Goal.for_user
      |> Repo.get!(id)

    render conn, "show.json", %{goal: goal}
  end

  def create(conn, _) do
  end

  def update(conn, _) do
  end

  def delete(conn, _) do
  end
end

web/controllers/goal_controller.ex
defmodule Steps.GoalController do
  use Steps.Web, :controller

  alias Steps.{Auth, Goal}

  def action(conn, _) do
    apply(__MODULE__,
          action_name(conn),
          [conn, conn.params, Auth.current_user(conn)])
  end

  def index(conn, _params, user) do
    goals =
      user
      |> Goal.for_user(with_steps: true)
      |> Repo.all

    render(conn, "index.html", goals: goals)
  end

  def new(conn, _params, user) do
    changeset =
      user
      |> build_assoc(:goals)
      |> Goal.changeset

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"goal" => goal_params}, user) do
    changeset =
      user
      |> build_assoc(:goals)
      |> Goal.changeset(goal_params)

    case Repo.insert(changeset) do
      {:ok, goal} ->
        conn
        |> put_flash(:info, "Goal created successfully.")
        |> redirect(to: goal_path(conn, :show, goal))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, user) do
    goal = user
           |> Goal.for_user(with_steps: true)
           |> Repo.get!(id)

    render(conn, "show.html", goal: goal)
  end

  def edit(conn, %{"id" => id}, user) do
    goal = user
           |> Goal.for_user
           |> Repo.get!(id)
    changeset = Goal.changeset(goal)
    render(conn, "edit.html", goal: goal, changeset: changeset)
  end

  def update(conn, %{"id" => id, "goal" => goal_params}, user) do
    goal = user
           |> Goal.for_user
           |> Repo.get!(id)
    changeset = Goal.changeset(goal, goal_params)

    case Repo.update(changeset) do
      {:ok, goal} ->
        conn
        |> put_flash(:info, "Goal updated successfully.")
        |> redirect(to: goal_path(conn, :show, goal))
      {:error, changeset} ->
        render(conn, "edit.html", goal: goal, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, user) do
    goal = user
           |> Goal.for_user
           |> Repo.get!(id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(goal)

    conn
    |> put_flash(:info, "Goal deleted successfully.")
    |> redirect(to: goal_path(conn, :index))
  end
end

web/views/goal_view.ex
defmodule Steps.GoalView do
  use Steps.Web, :view

  def title(:new, _), do: "Set New Goal"
  def title(:show, conn), do: goal_name(conn)
  def title(:edit, _), do: "Edit Goal"
  def title(_, _), do: "Goals"

  def goal_name(conn) do
    "#{conn.assigns[:goal].name}"
  end
end

web/templates/goal/_dates_with_steps.html.eex
<div class="goal-step-dates">
  <%= for {_, step} <- dates_with_steps(@goal) do %>
    <%= if step do %>
      <a class="goal-step-date goal-step-date-completed"
        tabindex="0"
        data-toggle="popover"
        data-placement="bottom"
        data-animation="pop"
        data-content="<%= step_short_summary(step) %>">
      </a>
    <% else %>
      <div class="goal-step-date">
      </div>
    <% end %>

  <% end %>
</div>

web/templates/goal/_form.html.eex
<fieldset>
  <%= form_for @changeset, @action, fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <p>
      <%= label f, :name %>
      <%= text_input f, :name %>
      <%= error_tag f, :name %>
    </p>

    <p>
      <%= label f, :description %>
      <%= textarea f, :description %>
      <%= error_tag f, :description %>
    </p>

    <p>
      <%= submit "Submit" %>
    </p>
  <% end %>
</fieldset>

web/templates/goal/_steps.html.eex
<div class="steps-list">
  <div class="steps-list-header-row header-row">
    <h2>
      Step Log
    </h2>
    <ul class="header-action-items">
      <li class="header-action-item new new-step">
        <%= link "Record Step", to: goal_step_path(@conn, :new, @goal) %>
      </li>
    </ul>
  </div>

  <%= if Enum.empty?(@steps) do %>
    No steps recorded yet.
  <% end %>

  <%= for step <- sort_steps_by_date_desc(@steps) do %>

    <div class="steps-list-item">
      <div class="header-row">
        <h3 class="steps-list-item-date">
          <%= formatted_date(step.date) %>
        </h3>

        <ul class="header-action-items">
          <li class="header-action-item edit edit-step">
            <%= link "Edit", to: goal_step_path(@conn, :edit, @goal, step) %>
          </li>
          <li class="header-action-item delete delete-step">
            <%= link "Delete", to: goal_step_path(@conn, :delete, @goal, step), method: :delete, data: [confirm: "Are you sure?"] %>
          </li>
        </ul>

      </div>

      <div class="step-notes">
        <%= step.notes %>
      </div>
    </div>

  <% end %>
</div>

web/templates/goal/dates_with_steps.html.eex
<div class="goal-step-dates">
  <%= for {_, step} <- dates_with_steps(@goal) do %>
    <%= if step do %>
      <a class="goal-step-date goal-step-date-completed"
        tabindex="0"
        data-toggle="popover"
        data-placement="bottom"
        data-animation="pop"
        data-content="<%= step_short_summary(step) %>">
      </a>
    <% else %>
      <div class="goal-step-date">
      </div>
    <% end %>

  <% end %>
</div>

web/templates/goal/edit.html.eex
<%= Steps.SharedView.back_link(goal_path(@conn, :show, @goal)) %>

<h1>Edit goal</h1>

<%= render "_form.html", changeset: @changeset,
                         action: goal_path(@conn, :update, @goal) %>

web/templates/goal/form.html.eex
<fieldset>
  <%= form_for @changeset, @action, fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <p>
      <%= label f, :name %>
      <%= text_input f, :name %>
      <%= error_tag f, :name %>
    </p>

    <p>
      <%= label f, :description %>
      <%= textarea f, :description %>
      <%= error_tag f, :description %>
    </p>

    <p>
      <%= submit "Submit" %>
    </p>
  <% end %>
</fieldset>

web/templates/goal/index.html.eex
<div class="header-row">
  <h1>
    Goals
  </h1>
  <ul class="header-action-items">
    <li class="header-action-item new new-goal">
      <%= link "New goal", to: goal_path(@conn, :new) %>
    </li>
  </ul>
</div>


<%= for goal <- @goals do %>
  <div class="goal-index-item">

    <div class="header-row">
      <h2 class="goal-name">
        <%= link goal.name, to: goal_path(@conn, :show, goal) %>
      </h2>
      <ul class="header-action-items">
        <li class="header-action-item new new-step">
          <%= link "Record Step", to: goal_step_path(@conn, :new, goal) %>
        </li>
      </ul>
    </div>

    <%= Steps.StepView.render "_dates_with_goal_steps.html", goal: goal %>

  </div>
<% end %>

web/templates/goal/new.html.eex
<%= Steps.SharedView.back_link(goal_path(@conn, :index)) %>

<h1>New Goal</h1>

<%= render "_form.html", changeset: @changeset,
                         action: goal_path(@conn, :create) %>

web/templates/goal/show.html.eex
<%= Steps.SharedView.back_link(goal_path(@conn, :index)) %>

<div class="header-row">
  <h1 class="goal-name">
    <%= @goal.name %>
  </h1>
  <ul class="header-action-items">
    <li class="header-action-item edit edit-goal">
      <%= link "Edit", to: goal_path(@conn, :edit, @goal) %>
    </li>
    <li class="header-action-item delete delete-goal">
      <%= link "Delete", to: goal_path(@conn, :delete, @goal), method: :delete, data: [confirm: "Are you sure?"] %>
    </li>
  </ul>
</div>

<div class="goal-description">
  <%= @goal.description %>
</div>

<%= Steps.StepView.render "_dates_with_goal_steps.html", goal: @goal %>

<%= Steps.StepView.render "_goal_steps.html", conn: @conn, goal: @goal %>